version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 docker-entrypoint.sh node index.js
    networks:
      - appnet
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - appnet

  nginx:
    image: nginx:1.20.1-alpine
    container_name: nginx
    tty: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    networks:
      - appnet
    depends_on:
      - app
      - db

networks:
  appnet:
    driver: bridge
